# Generated by Django 5.1.4 on 2025-01-16 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidates_for_Mayor',
            new_name='CandidatesForDeputymayor',
        ),
        migrations.RenameModel(
            old_name='Candidates_for_deputymayor',
            new_name='CandidatesForMayor',
        ),
        migrations.RenameField(
            model_name='candidatesfordeputymayor',
            old_name='candidate_mayor',
            new_name='candidate_dep_mayor',
        ),
        migrations.RenameField(
            model_name='candidatesformayor',
            old_name='candidate_dep_mayor',
            new_name='candidate_mayor',
        ),
    ]
