# Generated by Django 5.1.4 on 2025-01-14 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Candidates_for_deputymayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=300)),
                ('votes_received', models.IntegerField()),
                ('party_associated', models.CharField(max_length=100)),
                ('election_promise', models.CharField(max_length=500)),
                ('candidate_dep_mayor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidates_for_Mayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=300)),
                ('votes_received', models.IntegerField()),
                ('party_associated', models.CharField(max_length=100)),
                ('election_promise', models.CharField(max_length=500)),
                ('candidate_mayor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
