# Generated by Django 5.1.4 on 2025-01-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_rename_candidates_for_mayor_candidatesfordeputymayor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterprofile',
            name='voter_id',
            field=models.CharField(max_length=10),
        ),
    ]
