# Generated by Django 5.1.4 on 2025-01-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_alter_voterprofile_voter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesfordeputymayor',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='candidatesformayor',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidatesformayor',
            name='votes_received',
            field=models.IntegerField(default='0'),
        ),
    ]
