# Generated by Django 5.1.4 on 2025-04-15 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_alter_vote_voter_delete_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopDeputyMayorCandidate',
            fields=[
            ],
            options={
                'verbose_name': 'Top Voted Deputy Mayor',
                'verbose_name_plural': 'Top Voted Deputy Mayor',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('election.candidatesfordeputymayor',),
        ),
        migrations.CreateModel(
            name='TopMayorCandidate',
            fields=[
            ],
            options={
                'verbose_name': 'Top Voted Mayor',
                'verbose_name_plural': 'Top Voted Mayor',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('election.candidatesformayor',),
        ),
    ]
