# Generated by Django 5.1.4 on 2025-04-18 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_topdeputymayorcandidate_topmayorcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='general_memeber_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes_for_general_member', to='election.candidatesfordeputymayor'),
        ),
        migrations.CreateModel(
            name='CandidatesForGeneralMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_type', models.CharField(default='general_member', max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='1.jpg', upload_to='')),
                ('area', models.CharField(max_length=300)),
                ('votes_received', models.IntegerField(default=0)),
                ('party_associated', models.CharField(max_length=100)),
                ('election_promise', models.CharField(max_length=500)),
                ('candidate_members', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopGeneralMemberCandidate',
            fields=[
            ],
            options={
                'verbose_name': 'Top Voted General Members',
                'verbose_name_plural': 'Top Voted General Members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('election.candidatesforgeneralmembers',),
        ),
    ]
