# Generated by Django 5.1.4 on 2025-01-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_candidatesfordeputymayor_candidate_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoterProfile',
            new_name='Voters',
        ),
        migrations.AlterField(
            model_name='candidatesformayor',
            name='votes_received',
            field=models.IntegerField(default=0),
        ),
    ]
