# Generated by Django 5.1.4 on 2025-04-18 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_vote_general_memeber_candidate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='general_memeber_candidate',
        ),
        migrations.AddField(
            model_name='vote',
            name='general_member_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes_for_general_member', to='election.candidatesforgeneralmembers'),
        ),
    ]
