# Generated by Django 5.1.4 on 2025-04-19 10:40

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_votingwindow_remove_vote_general_memeber_candidate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalVoters',
            fields=[
            ],
            options={
                'verbose_name': 'Voters',
                'verbose_name_plural': 'Voters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('election.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='votingwindow',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
