# Generated by Django 5.1.4 on 2025-01-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_rename_voterprofile_voters_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voters',
            new_name='Voter',
        ),
    ]
